name: udp
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: http://github.com/xenoken/udp
repository: http://github.com/xenoken/udp
issue_tracker: http://github.com/xenoken/udp/issues
author: Ken <ekeohak@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
